name: continous integration of python appliacation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python 3.9
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/test_main.py

      - name: Build package
        run: |
          source venv/bin/activate
          python setup.py sdist bdist_wheel

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: my-python-app-package
          path: dist/
